trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**src/test/java/MyTest.xml'
    goals: 'package'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target/${artifactName}.war'
    ArtifactName: java-app-artifact

