trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  displayName: Install dependencies, Build & Package (.war file)
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**src/test/java/MyTest.xml'
    goals: 'package'
    
- task: PublishBuildArtifacts@1
  displayName: Publish build artifact
  inputs:
    PathtoPublish: 'target/helloworld.war'
    ArtifactName: java-app-artifact

